string(ASCII 27 esc)  # = \x1b
set(esc_regex "${esc}\\[(m|1m|3[1-7]m|1;3[1-7]m)")

if(NOT WIN32)
  set(colorReset  "${esc}[m")
  set(colorBold   "${esc}[1m")
  set(red         "${esc}[31m")
  set(green       "${esc}[32m")
  set(yellow      "${esc}[33m")
  set(blue        "${esc}[34m")
  set(magenta     "${esc}[35m")
  set(cyan        "${esc}[36m")
  set(white       "${esc}[37m")
  set(boldRed     "${esc}[1;31m")
  set(boldGreen   "${esc}[1;32m")
  set(boldYellow  "${esc}[1;33m")
  set(boldBlue    "${esc}[1;34m")
  set(boldMagenta "${esc}[1;35m")
  set(boldCyan    "${esc}[1;36m")
  set(boldWhite   "${esc}[1;37m")
endif()
